#pragma once

#include"List.h"
#include"Sprite.h"

/* khai báo 1 define viết tắt cho chữ SpriteManager::getSprite */
#define SPR SpriteManager::getSprite

/* ta tạo 1 sprite info để lưu thông tin của các sprite */
enum SPRITE_INFO
{
	/* đối tượng không có hình ảnh ta sẽ đặt số âm */
	SPRITE_INFO_STAIR = -3,
	SPRITE_INFO_SHURIKEN_ITEM = -2,
	SPRITE_INFO_GROUND = -1,

	/* đối tượng có hình ảnh ta sẽ đặt số dương */
	SPRITE_INFO_RYU = 0,
	SPRITE_INFO_SWORDMAN = 1,
	SPRITE_INFO_PANTHER = 2,
	SPRITE_INFO_BAT = 3,
	SPRITE_INFO_BROWN_BIRD = 4,
	SPRITE_INFO_BANSHEE = 5,
	SPRITE_INFO_SHOOTER = 7,
	SPRITE_INFO_BANSHEE_WEAPON = 8,
	SPRITE_INFO_SHOOTER_WEAPON = 9,
	SPRITE_MISC = 10,
	SPRITE_EXPLOSION = 11,
	SPRITE_BUTTER_FLY = 12,
	SPRITE_ITEM_1 = 13,
	SPRITE_ITEM_SHURIKEN_SMALL = 14,
	SPRITE_BIRD_STATIC = 15,
	SPRITE_ITEM_2 = 16,
	SPRITE_ITEM_SHURIKEN_2 = 17,
	SPRITE_ITEM_MONEY_BAG_BLUE = 18,
	SPRITE_ITEM_MONEY_BAG_RED = 19,
	SPRITE_INFO_RUNNER = 20,
	SPRITE_INFO_BAAZOKA = 21,
	SPRITE_ITEM_FIRE = 22,
	SPRITE_ITEM_STOP_WATCH = 23,
	SPRITE_BOSS = 24,

	SPRITE_COUNT
};

enum MISC_SPRITE_ID
{
	MISC_SPRITE_ID_NUMBER,
	MISC_SPRITE_ID_MORNING_STAR,
	MISC_SPRITE_ID_LOST_HEALTH,
	MISC_SPRITE_ID_KNIFE_ITEM,
	MISC_SPRITE_ID_TORCH,
	MISC_SPRITE_ID_EXPLOSION_EFFECT,
	MISC_SPRITE_ID_CANDLE,
	MISC_SPRITE_ID_MERMAN_BULLET,
	MISC_SPRITE_ID_ITEM_MORNING_STAR,
	MISC_SPRITE_ID_ITEM_SMALLHEART,
	MISC_SPRITE_ID_ITEM_WATER,
	MISC_SPRITE_ID_ITEM_BIGHEART,
	MISC_SPRITE_ID_ITEM_DAGGER,
	MISC_SPRITE_ID_ITEM_HOLYWATER,
	MISC_SPRITE_ID_ITEM_HOLYCROSS,
	MISC_SPRITE_ID_ITEM_AXE,
	MISC_SPRITE_ID_ITEM_GOLDPOTION,
	MISC_SPRITE_ID_ITEM_STOPWATCH,
	MISC_SPRITE_ID_ITEM_BREAK_WALL1,
	MISC_SPRITE_ID_ITEM_BREAK_WALL,
	MISC_SPRITE_ID_ITEM_400PTS,
	MISC_SPRITE_ID_ITEM_700PTS,
	MISC_SPRITE_ID_ITEM_1000PTS,
	MISC_SPRITE_ID_ITEM_BOOMERANG,
	MISC_SPRITE_ID_BOOMERANG,
	MISC_SPRITE_ID_SHURIKEN_BIG,
};

class SpriteManager
{
	/* ta lưu tất cả sprite ở đây */
	List<Sprite*> sprites;

	/* singleton pattern */
	static SpriteManager* instance;
public:
	static SpriteManager* getInstance();

	/* dùng để lấy sprite từ spriteManager */
	static Sprite* getSprite(int spriteInfo);

	SpriteManager();
	~SpriteManager();
};

